services:
  app:
    image: golang
    working_dir: /app
    volumes:
      - ./:/app
      - /var/www/owwo/shared:/var/www/owwo/shared
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - TZ=Europe/Moscow
    command:
      sh -c "go run ./cmd/server/main.go"
