version: '3.8'

services:
  nginx:
    build:
      network: host
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - fcgi
    networks:
      - web-network

  fcgi:
    build:
      network: host
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/web
    ports:
      - "9000:9000"
      - "8082:8082"
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
