FROM alpine:latest

ENV CONFIG_PATH=/web/constants/docker.env

RUN apk add --no-cache \
	gcc \
	make \
	musl-dev \
	fcgi-dev \
	spawn-fcgi \
	nodejs \
	npm

WORKDIR /web

COPY . .

RUN npm install

CMD ["npm", "run", "watch"]
